// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbuctojuytpettvbvhiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidWN0b2p1eXRwZXR0dmJ2aGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzY1NTUsImV4cCI6MjA2ODUxMjU1NX0.cLkP46FIjAEb0aKgUY67AFKfmhJk5gc-TMMTGj17BYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});